package com.cisco.cpaas.voice.type;

import com.cisco.cpaas.voice.engine.Voice;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import lombok.Builder;
import lombok.Value;

/** Voice call audio files that are generated by a text to speech system. */
@Value
@Builder(builderClassName = "Builder")
public final class TtsAudio implements Audio {

  /** The format of the data in the text field. */
  public enum TextFormat {
    /** Plain text. */
    TEXT,
    /** Speech Synthesis Markup language text. */
    SSML
  }

  private static final String TYPE = "TTS";

  private final Type type = Type.TTS;
  private final String text;
  private final TextFormat textFormat;
  private final Integer loop;
  @JsonUnwrapped private final Voice voice;

  /**
   * Create a new text to speech audio message with default values.
   *
   * @param text The dialog that will be spoken.
   * @param voice The voice that will dictate the dialog to the callee.
   * @return The new audio object.
   */
  public static TtsAudio of(String text, Voice voice) {
    return new TtsAudio(text, TextFormat.TEXT, null, voice);
  }

  /**
   * Create a new text to speech audio message using SSML formatted text and default values.
   *
   * @param ssml The SSML that will be used to dictate the message.
   * @param voice The voice that will dictate the dialog to the callee.
   * @return The new audio object.
   */
  public static TtsAudio ofSsml(String ssml, Voice voice) {
    return new TtsAudio(ssml, TextFormat.SSML, null, voice);
  }

}
